### ISSUE TITLE
How do you display graphs and save them?

### ISSUE THREAD

**Issue by endrebak** [kyleam/snakemake-mode#12]
I got the latest version from elpa, and tried `M-x snakemake-graph-mode <RET>` and nothing happens, except that the minibuffer says `Snakemake-graph-mode enabled`. When I then use `M-x snakemake-graph-save <RET>` I get the message `Not in snakemake graph buffer`.

Am I doing something wrong? I'd just like to create a graph of my current pipeline and view it in emacs.

My version is `20160417.2206`.

**Comment by kyleam** [comment]
The entry point is `snakemake-graph`.  This displays a buffer with the
graph.  From the buffer, you can save the graph with `C-c C-s`
(`snakemake-graph-save`).

But, as discussed in #11, the depends on a setup that is centered
around a "Snakefile".  I've added a `snakemake-graph-this-file`
command (efbfad4) that should work for your setup.

`M-x snakemake-graph-this-file` from your Snakemake mode buffer will
display this buffer, and `C-c C-s` from the graph buffer will save
it to a file.  See `snakemake-graph-this-file`'s docstring for more
details.

**Comment by endrebak** [comment]
Thanks. Haven't had the time to try it out but will do soon. I think having a single snakefile would be easier in many cases, but in my case it would be way too long. I have never used targets so will look up exactly what they are and how to use them. Will probably make understanding your code easier.

**Comment by kyleam** [comment]
> I have never used targets so will look up exactly what they are and
> how to use them. Will probably make understanding your code easier.

Targets are the positional arguments that tell Snakemake what to
build.

    $ snakemake [options] -- [target ...]

They can be either rule names or file names.  As a special
case, when one is not specified, the first rule is built.
