### ISSUE TITLE
hs-special-modes-alist not working

### ISSUE THREAD

**Issue by endrebak** [kyleam/snakemake-mode#14]
I have the following snippet for `hs-special-modes-alist`, but it does not work:

```
;;; HideShow

(add-to-list 'hs-special-modes-alist '(snakemake-mode "^rule .*\\>" nil "#" nil
                                                      nil))
```

The regex works if I try it with `re-search` so I am confused about what is wrong.

**Comment by endrebak** [comment]
Come to think of it, I really should have posted this to the emacs stack exchange. Cannot delete, unfortunately.

**Comment by endrebak** [comment]
I am guessing it is because I have neither defined an end for my block, nor a `forward-sexp-function`. Only the latter is possible, so that must probably be done first.

**Comment by kyleam** [comment]
> I am guessing it is because I have neither defined an end for my
> block, nor a `forward-sexp-function`. Only the latter is possible, so
> that must probably be done first.

Thanks for looking into setting up `hs-special-modes-alist`.  Your guess
sounds right.

I was going to suggest you check snakemake-in-rule-or-subworkflow-block-p
to see how rule blocks are recognized.  But, revisiting that function, I
think there are at least a couple cases that aren't handled correctly
(rule blocks that are indented under, say, an if statement; the function
relies on no blanks between rule lines even though this is legal
syntax).  I should rewrite it, and then the forward-sexp-function should
pretty much fall out of that.

However, I don't think I'll find time to do that for another week or
two.  (In the meantime, I'll probably be pretty unresponsive in general,
aside from merging #13.)

**Comment by endrebak** [comment]
Thanks!

**Comment by kyleam** [comment]
Commit 2ddaa5a adds `snakemake-end-of-defun`, which I think you should
be able to use here.

**Comment by endrebak** [comment]
Thanks!

I do not know when I will have the time to try it, though.

And as this was more of a misplaced question than an issue you may close it.
