### ISSUE TITLE
Odd indent for all lists

### ISSUE THREAD

**Issue by nasfarley88** [kyleam/snakemake-mode#19]
With Emacs 24.5.1 (with Spacemacs) I get strange indentation:

```
 rule dummy:
     input:
         "dummy_input_1",
           "dummy_input_2", # This line is indented more?
           "dummy_input_3",
```

Is this the intended behaviour?

**Comment by nasfarley88** [comment]
Nevermind, I thought I had the latest git version of the package but I didn't. In the latest git it is fixed.

**Comment by kyleam** [comment]
Great, thanks for checking the latest version.
