### ISSUE TITLE
R code block syntax highlighting

### ISSUE THREAD

**Issue by elsherbini** [kyleam/snakemake-mode#21]
Let me preface this by saying that I am very new to emacs and I'm checking it out mostly because of snakemake-mode. Thanks for making this!

I'm using spacemacs, and I installed mmm-mode and snakemake-mode.

In my user-config function I have the following code:

`(setq mmm-global-mode 'maybe)`

When I load up a Snakefile, the code is highlighted, but code inside an `R()` call isn't.
![screenshot from 2017-02-26 18-58-53](https://cloud.githubusercontent.com/assets/2695357/23345064/aeb95ba2-fc55-11e6-9680-ca519950e69f.png)

Any ideas what I might be doing wrong?

**Comment by kyleam** [comment]
> Let me preface this by saying that I am very new to emacs and I'm
> checking it out mostly because of snakemake-mode. Thanks for making
> this!

You're welcome!  Any feedback is greatly appreciated.

> I'm using spacemacs, and I installed mmm-mode and snakemake-mode.
>
> In my user-config function I have the following code:
>
> `(setq mmm-global-mode 'maybe)`

> When I load up a Snakefile, the code is highlighted, but code inside
> an `R()` call isn't.
>
> Any ideas what I might be doing wrong?

You need to call snakemake-mode-setup-mmm as well, I think.  I must
admit that I've never used the mmm-mode functionality (which was
contributed by @endrebak), but

   (snakemake-mode-setup-mmm)
   (setq mmm-global-mode 'maybe)

seems to do the trick.

**Comment by endrebak** [comment]
Also, consider using the script directive to point to an R-script instead of the R-function. Separation of the DAG-logic from the code of each rule is good. Plus you get R-syntax highlighting with the ESS mode then :)

**Comment by kyleam** [comment]
@elsherbini Hopefully you were able to get things working using the
snippet above.  If not, feel free to re-open this issue.
