### ISSUE TITLE
configfile should have different highlighting when used as subworkflow directive

### ISSUE THREAD

**Issue by endrebak** [kyleam/snakemake-mode#23]
A picture says a thousand words:

![screen shot 2017-10-30 at 14 58 32](https://user-images.githubusercontent.com/17778898/32174757-06264a78-bd83-11e7-8cf9-2b3a11f19d97.png)

This should be really low priority I guess :)

**Comment by kyleam** [comment]
> This should be really low priority I guess :)

low priority, but also an easy fix :)

Thanks for catching this.
