### ISSUE TITLE
indentation problems

### ISSUE THREAD

**Issue by epruesse** [kyleam/snakemake-mode#26]
Since updating to the newest version, I've got problems with the indentation. For some reason, the set of indentation levels rotated through iteratively is one too short. I.e. the maximum indentation I get with `<tab>` is equal to the previous statement, even if that was a field. It starts at the right place after `<return>`, but tab won't get me back there...

```
rule:
message:
```

I did upgrade a bunch of things at once, of course, so the cause might be somewhere else. Indentation does work for me in python-mode though.

Any suggestions on what might be causing this?

**Comment by kyleam** [comment]
> Since updating to the newest version

Do you happen to recall what version(-ish) you upgraded from?

> Any suggestions on what might be causing this?

Hmm, I'm not having any luck reproducing this (Emacs 25.3, GNU/Linux).
Starting with point in front of "message", TAB indents it four spaces.

You could try debugging `snakemake--calculate-indentation`,
particularly

https://github.com/kyleam/snakemake-mode/blob/6cf6d20db2e5253ce3f86e302651faa28f220aa7/snakemake-mode.el#L258-L269

That should return the value of `snakemake-indent-field-offset` (4 by
default).

> I did upgrade a bunch of things at once, of course, so the cause might be somewhere else.

You could also try testing with emacs -Q, and then just loading
snakemake-mode and its dependencies (dash, magit-popup).

If you have a local clone of the repo, running `make test` would tell
you if the indentation tests (ran with emacs -Q) are passing for you.

What version of Emacs are you using?
