### ISSUE TITLE
snakemake-mode highlighting not working with emacs 27

### ISSUE THREAD

**Issue by CreRecombinase** [kyleam/snakemake-mode#29]
After upgrading emacs to version 27 syntax highlighting in snakemake-mode doesn't seem to work anymore. The `*Messages*` buffer shows:
```
Error during redisplay: (jit-lock-function 1) signaled (void-function python-font-lock-keywords-level-1)
```

I struggle with elisp but my best guess is that this has something to do with [this change in python.el](https://emba.gnu.org/emacs/emacs/commit/36b64e087ea332505ae9a40f90af45e678db2255)

**Comment by kyleam** [comment]
Thanks for reporting and for pointing to the likely culprit.  I'll take a look some time later this week.

**Comment by kyleam** [comment]
Should be all set.  Please let me know if you still run into an issue on your end.
