### ISSUE TITLE
No indentation on pressing TAB, just error  

### ISSUE THREAD

**Issue by sonia-t** [kyleam/snakemake-mode#4]
I'm having issues using TAB for indentation when viewing a Snakefile in emacs with snakemake-mode.

When I open a Snakefile in emacs, the syntax highlighting looks correct, but if try to use TAB for indentation, the cursor stays in column 0 and instead I get the error :
`Symbol's function definition is void: looking-at-p`

Followed directions here:
http://melpa.org/#/snakemake-mode

My setup:
* GNU Emacs 22.1.1 
* snakemake-mode commit SHA 295bbfbc94727691d7e9919abf9f358ab7a6b241
* file snakemake-mode.el in my ~/.emacs.d 
* In my ~/.emacs :
```
(add-to-list 'load-path "~/.emacs.d/")
(require 'snakemake-mode)
```
* Also tried in my ~/.emacs :
```
(load-file "~/.emacs.d/snakemake-mode.el")
```

Next I'll try installing from MELPA but i thought this should be documented somewhere. Of course, any insight appreciated.

**Comment by sonia-t** [comment]
TAB indent functionality works with Emacs 24.3  ... not sure why macOS system emacs is so old :(

**Comment by kyleam** [comment]
Great, glad it's working for you now.  The reason that Snakemake mode depends on Emacs 24 is that it uses python.el, which wasn't included until version 24.
