### ISSUE TITLE
Rules not properly indented after copy/pasting

### ISSUE THREAD

**Issue by endrebak** [kyleam/snakemake-mode#8]
When I copy/paste a rule it looks like this afterwards:

```
  rule create_design_matrix:
  output:
  outfile = "tmpdir/run_csaw_{input_use}/design_matrix.csv"
  run:
  time = pd.Series(list(range(0, 25, 3)) * 2)
  values = time * 2 * np.pi / 17
  sine = np.sin(values)
  cosine = np.cos(values)

        design = pd.concat([time, sine, cosine], axis=1)
        design.columns = "Time Sine Cosine".split()
        design.to_csv(output.outfile, index=False, sep=" ")
```

Normally, I'd just mark the region and press `=` (`evil-indent`) to get the proper indentation, but that isn't working either. I'll prolly look into it myself eventually, but would love input on what you think is happening/best ways to fix.

**Comment by kyleam** [comment]
> When I copy/paste a rule it looks like this afterwards:

Hmm, pasting rules preserves the indentation for me, but I think that's
because I have electric-indent-mode disabled.

> Normally, I'd just mark the region and press `=` (`evil-indent`) to
> get the proper indentation, but that isn't working either.

I had left indent-region-function [1] at its default value
(python-indent-region), which isn't appropriate for rule blocks.  Please
let me know how 66f0d24 works for you.  In addition to making
indent-region useful, I'm hoping it solves the electric-indent-mode
paste issue.

[1] I'm assuming that evil just calls indent-region underneath.

**Comment by endrebak** [comment]
I only evaled the two new files, did not install them in the `.emacs.d/elpa/` folder, but this seems to have fixed my issues.

**Comment by endrebak** [comment]
I am experiencing the same problem with `yasnippets`.

This rule:

```
# -*- mode: snippet -*-
# name: rule
# key: rl
# --
rule $1:
    input:
        infile = ""
    output:
        outfile = ""
    $0
```

expands into this:

```
rule :
input:
infile = ""
output:
outfile = ""
```

**Comment by kyleam** [comment]
This should work as of 5350b3b (Allow spaces after rule/subworkflow
name, 2016-05-03).  You can also set [yas-indent-line][yi] to `fixed`
force the snippet to be indented as is.

[yi]: https://capitaomorte.github.io/yasnippet/snippet-reference.html#yas-indent-line
